# Name of workflow
name: Node CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        run: make lint
      - name: webpack
        run: make webpack
      - name: build
        run: make build
      - name: publish
        run: make publish
      - name: install
        run: make install
